### POST Admin
POST http://localhost:8080/admin
Authorization: Basic qwe qwe
content-type:application/json

{
  "login": "qwe1",
  "surname": "qwe1",
  "name": "qwe",
  "patronymic": "qwe",
  "password": "qwe",
  "email": "qwe1@qwe.qwe",
  "salary": 30000
}

### POST Admin
POST http://localhost:8080/admin
Authorization: Basic asd asd
content-type:application/json

{
  "login": "qwe2",
  "surname": "qwe2",
  "name": "qwe",
  "patronymic": "qwe",
  "password": "qwe",
  "email": "qwe1@qwe.qwe",
  "salary": 30000
}

### POST Admin
POST http://localhost:8080/admin
Authorization: Basic asddddd asddddd
content-type:application/json

{
  "login": "qwe2",
  "surname": "qwe2",
  "name": "qwe",
  "patronymic": "qwe",
  "password": "qwe",
  "email": "qwe1@qwe.qwe",
  "salary": 30000
}